---
  - lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp="{{ item.var }}=" line="{{ item.var }}={{ item.value }}"
    with_items:
      - { var: "ServerActive", value: "{{zabbix_agent_server}}:{{zabbix_agent_server_port}}"}
      - { var: "Hostname", value: "{{zabbix_agent_hostname_prefix}}{{ansible_hostname}}"}
      - { var: "StartAgents", value: "{{zabbix_agent_start_agents}}"}
      - { var: "HostMetadata", value: "{{ zabbix_agent_metadata }}"}
      - { var: "RefreshActiveChecks", value: "{{zabbix_agent_refresh_active_checks}}"}
      - { var: "DebugLevel", value: "{{zabbix_agent_debug_level}}"}
    notify: restart zabbix-agent
     
  - lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp="{{ item }}=" state=absent
    with_items:
      - "Server="
      - "Include="
    notify: restart zabbix-agent
